title                   : On a Darkling Whim
title_separator         : "-"
subtitle                : >-
  Dark stories, tales of whimsy and random brain droppings.
description             : >-
  Dark stories, tales of whimsy and random brain droppings.
url                     : https://douglangille.ca 
baseurl                 : /
github                  : [metadata]
github_username         : douglangille
repository              : douglangille/website
name                    : "Doug Langille"
email                   : me@douglangille.ca

teaser                  : /assets/images/white500x300.jpg
logo                    : 
masthead_title          :

theme                   : minimal-mistakes-jekyll
minimal_mistakes_skin   : default

words_per_minute        : 200

markdown                : kramdown
excerpt_separator       : "\n\n"
encoding                : "utf-8"

permalink               : /:title/
breadcrumbs             : false

locale                  : en-CA
timezone                : America/Halifax

include:
  - _pages

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-redirect-from

comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  giscus:
    repo_id              : # Shown during giscus setup at https://giscus.app
    category_name        : # Full text name of the category
    category_id          : # Shown during giscus setup at https://giscus.app
    discussion_term      : # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : # '1' for enabled (default), '0' for disabled
    theme                : # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :

search                   : false
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
lunr:
  search_within_pages    : # true, false (default)
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true

google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)

author:
  name                  : "Doug Langille"
  avatar                : "/assets/images/bio-photo.jpg"
  bio                   : "hack writer & shameless technophile"
  location              : "Nova Scotia"
  email                 : me@douglangille.ca
  links:
    - label             : "LinkedIn"
      icon              : "fab fa-fw fa-linkedin"
      url               : "https://www.linkedin.com/in/douglangille"
#    - label             : "Mastodon"
#      icon              : "fab fa-fw fa-mastodon"
#      url               : "https://douglangille.ca/@douglangille"
    - label             : "Substack"
      icon              : "fa-regular fa-fw fa-newspaper"
      url               : "https://douglangille.substack.com"

footer:
  links:
    - label             : "LinkedIn"
      icon              : "fab fa-fw fa-linkedin"
      url               : "https://www.linkedin.com/in/douglangille/"
#    - label             : "Mastodon"
#      icon              : "fab fa-fw fa-mastodon"
#      url               : "https://douglangille.ca/@douglangille"

pagination:
  enabled               : true
  per_page              : 12
  permalink             : '/page:num/'
  title                 : ''
  sort_field            : 'date'
  sort_reverse          : true
  trail:
    before              : 2
    after               : 2

category_archive:
  type                  : jekyll-archives #autopages
  path                  : /
tag_archive:
  type                  : jekyll-archives #autopages
  path                  : /

autopages:
  enabled               : true
  categories:
    layouts             : 
      - 'archive-taxonomy.html'
    permalink           : '/:cat'
  tags:
    layouts             : 
      - 'archive-taxonomy.html'
    permalink           : '/:tag'
  collections:
    layouts             : 
      - 'archive-taxonomy.html'
    permalink           : '/:coll'

related_by: tags or categories 
related_limit: 4            
related_categories: 1       
related_tags: 1    
related_template: archive-single.html
related_layout: grid

defaults:
  - scope:
      path              : ""
      type              : posts
    values:
      layout            : single
      author_profile    : true
      read_time         : true
      comments          : true
      share             : false
      related           : true
      show_date         : true
      overlay_filter    : .5
      classes           : wide
      excerpt           : ""
  - scope:
      path              : "_pages"
      type              : pages
    values:
      layout            : single
      author_profile    : true     
      read_time         : true
      comments          : true
      share             : false
      overlay_filter    : .5
      classes           : wide
  - scope:
      path              : ""
      type              : category
    values:
      comments          : false
      author_profile    : true     
      classes           : wide
      entries_layout    : grid
  - scope:
      path              : ""
      type              : tag
    values:
      comments          : false
      author_profile    : true     
      classes           : wide
      entries_layout    : grid

